name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, reopened ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Install dotnet coverage
      run: dotnet tool install --global dotnet-coverage

    - name: Install Sonar global tool
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Begin Sonar scan
      run: dotnet sonarscanner begin /k:"binarysenator_bongobin.hclparser" /o:"binarysenator" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
      
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet-coverage collect 'dotnet test' -f xml  -o 'coverage.xml'
      
    - name: End Sonar scan
      run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
